#logging.level.root= DEBUG

server.port=9000
management.server.port=9001
management.server.address=0.0.0.0
#management.endpoints.web.exposure.include=health,info,mappings

server.tomcat.max-part-count=100
#spring.mvc.format.date-time=yyyy-MM-dd'T'HH:mm:ss

# http://localhost:9001/actuator/health
management.endpoint.health.show-details=always

dbo.management=true

# http://localhost:9001/actuator/info
management.info.env.enabled=true
info.app.name=Sample RESTful Web Service with Spring Boot
info.app.description=Proof of Concept for a RESTful Web Service made with Spring Boot 4 targeting JDK 25

springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=/swagger/index.html

queue.url=http://localhost:9000
queue.enqueue.path=/queue/put

script.url=http://localhost:9000
script.process.path=/script/run

#db

spring.datasource.url=jdbc:postgresql://localhost:5432/etl
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=etl
spring.datasource.password=etl



spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
# Management

hibernate.hbm2ddl.auto.management=update

spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true

spring.manager.return.url=http://localhot:9000/return/task

executor.thread=2
scheduler.testInterval=5
app.restUrl=https://httpbin.org/json
#security.basic.enabled=false
#management.security.enabled=false
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# queue
queue.executor.thread=3
queue.scheduler.testInterval=5
sensor.scheduler.testInterval=5
