#logging.level.root= DEBUG

server.port=9000
management.server.port=9001
management.server.address=0.0.0.0
#management.endpoints.web.exposure.include=health,info,mappings

# http://localhost:9001/actuator/health
management.endpoint.health.show-details=always

# http://localhost:9001/actuator/info
management.info.env.enabled=true
info.app.name=Sample RESTful Web Service with Spring Boot
info.app.description=Proof of Concept for a RESTful Web Service made with Spring Boot 4 targeting JDK 25

springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=/swagger/index.html

queue.url=http://localhost:9000
queue.enqueue.path=/queue/put
#db

spring.datasource.url=jdbc:postgresql://localhost:5432/etl
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=etl
spring.datasource.password=etl


spring.jpa.hibernate.management.ddl-auto=update
spring.jpa.management.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
# Management


#spring.datasource.management.url=jdbc:postgresql://localhost:5432/etl?currentSchema=etl
#spring.datasource.management.driver-class-name=org.postgresql.Driver
hibernate.hbm2ddl.auto.management=update
#hibernate.dialect.management=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.management.username=etl
#spring.datasource.management.password=etl

#spring.jpa.properties.hibernate.transaction.jta.platform=org.springframework.boot.hibernate.SpringJtaPlatform
# queue

#spring.datasource.queue.url=jdbc:postgresql://localhost:5432/queue?currentSchema=queue
#spring.datasource.queue.driver-class-name=org.postgresql.Driver
#spring.datasource.queue.username=etl
#spring.datasource.queue.password=etl
#hibernate.hbm2ddl.auto.queue=update
#hibernate.dialect.queue=org.hibernate.dialect.PostgreSQLDialect


#hibernate.hbm2ddl.management.auto=true
#spring.jpa.hibernate.management.ddl-auto=update
#spring.jpa.management.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true


spring.manager.return.url=http://localhot:9000/return/task

executor.thread=2
scheduler.testInterval=5
app.restUrl=https://httpbin.org/json
#security.basic.enabled=false
#management.security.enabled=false
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# queue
queue.executor.thread=2